{% set name = "fps-retrolab" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_retrolab-{{ version }}.tar.gz
  sha256: e47206edea3af12084f367c1c8887ad984dd582bea6b5d79049317e164a0b401

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - fps-lab >=0.0.37,<1
    - fps-frontend <1
    - retrolab <1

test:
  imports:
    - fps_retrolab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/retrolab
  summary: An FPS plugin for the RetroLab API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/retrolab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
